-- COLEGIO.COLEGIO definition

-- Drop table

-- DROP TABLE COLEGIO.COLEGIO;

CREATE TABLE COLEGIO.COLEGIO (
	NOMBRE VARCHAR(100),
	IDCOLEGIO INTEGER DEFAULT AUTOINCREMENT: start 1 increment 1 NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
	CONSTRAINT COLEGIO_PK PRIMARY KEY (IDCOLEGIO)
);
CREATE UNIQUE INDEX SQL220216135105730 ON COLEGIO.COLEGIO (IDCOLEGIO);


-- COLEGIO.ESTUDIANTE definition

-- Drop table

-- DROP TABLE COLEGIO.ESTUDIANTE;

CREATE TABLE COLEGIO.ESTUDIANTE (
	IDESTUDIANTE INTEGER DEFAULT AUTOINCREMENT: start 1 increment 1 NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
	NOMBRE VARCHAR(100),
	CONSTRAINT ESTUDIANTE_PK PRIMARY KEY (IDESTUDIANTE)
);
CREATE UNIQUE INDEX SQL220216135447350 ON COLEGIO.ESTUDIANTE (IDESTUDIANTE);


-- COLEGIO.GRADO definition

-- Drop table

-- DROP TABLE COLEGIO.GRADO;

CREATE TABLE COLEGIO.GRADO (
	IDGRADO INTEGER DEFAULT AUTOINCREMENT: start 1 increment 1 NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
	GRADO VARCHAR(100),
	CONSTRAINT GRADO_PK PRIMARY KEY (IDGRADO)
);
CREATE UNIQUE INDEX SQL220216135019880 ON COLEGIO.GRADO (IDGRADO);


-- COLEGIO.PROFESOR definition

-- Drop table

-- DROP TABLE COLEGIO.PROFESOR;

CREATE TABLE COLEGIO.PROFESOR (
	IDPROFESOR INTEGER DEFAULT AUTOINCREMENT: start 1 increment 1 NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
	NOMBRE VARCHAR(100),
	CONSTRAINT PROFESOR_PK PRIMARY KEY (IDPROFESOR)
);
CREATE UNIQUE INDEX SQL220216135035120 ON COLEGIO.PROFESOR (IDPROFESOR);


-- COLEGIO.CURSO definition

-- Drop table

-- DROP TABLE COLEGIO.CURSO;

CREATE TABLE COLEGIO.CURSO (
	IDCURSO INTEGER DEFAULT AUTOINCREMENT: start 1 increment 1 NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
	IDCOLEGIO INTEGER,
	SALON VARCHAR(100),
	CONSTRAINT CURSO_PK PRIMARY KEY (IDCURSO),
	CONSTRAINT CURSO_FK2 FOREIGN KEY (IDCOLEGIO) REFERENCES COLEGIO.COLEGIO(IDCOLEGIO)
);
CREATE UNIQUE INDEX SQL220216134851471 ON COLEGIO.CURSO (IDCURSO);
CREATE INDEX SQL220216135355130 ON COLEGIO.CURSO (IDCOLEGIO);


-- COLEGIO.ASIGNATURA definition

-- Drop table

-- DROP TABLE COLEGIO.ASIGNATURA;

CREATE TABLE COLEGIO.ASIGNATURA (
	IDASIGNATURA INTEGER DEFAULT AUTOINCREMENT: start 1 increment 1 NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
	NOMBRE VARCHAR(100),
	IDPROFESOR INTEGER,
	IDESTUDIANTE INTEGER,
	IDGRADO INTEGER,
	IDCURSO INTEGER,
	CONSTRAINT ASIGNATURA_PK PRIMARY KEY (IDASIGNATURA),
	CONSTRAINT ASIGNATURA_FK FOREIGN KEY (IDESTUDIANTE) REFERENCES COLEGIO.ESTUDIANTE(IDESTUDIANTE),
	CONSTRAINT ASIGNATURA_FK4 FOREIGN KEY (IDCURSO) REFERENCES COLEGIO.CURSO(IDCURSO),
	CONSTRAINT ASIGNATURA_FK_1 FOREIGN KEY (IDPROFESOR) REFERENCES COLEGIO.PROFESOR(IDPROFESOR),
	CONSTRAINT ASIGNATURA_FK_3 FOREIGN KEY (IDGRADO) REFERENCES COLEGIO.GRADO(IDGRADO)
);
CREATE UNIQUE INDEX SQL220216135138530 ON COLEGIO.ASIGNATURA (IDASIGNATURA);
CREATE INDEX SQL220216143058290 ON COLEGIO.ASIGNATURA (IDESTUDIANTE);
CREATE INDEX SQL220216143058340 ON COLEGIO.ASIGNATURA (IDPROFESOR);
CREATE INDEX SQL220216143242200 ON COLEGIO.ASIGNATURA (IDGRADO);
CREATE INDEX SQL220217160407810 ON COLEGIO.ASIGNATURA (IDCURSO);